export const audioManifest = [
  'assist.card.scan.aadhaar',
  'assist.card.scan.pan',
  'assist.card.scan.epic',
  'assist.card.scan.ration',
  'assist.card.scan.bank',
  'assist.card.offer.pan',
  'assist.card.offer.epic',
  'assist.card.offer.ration',
  'assist.card.offer.bank',
  'assist.card.confirm.title',
  'assist.name',
  'assist.dob',
  'assist.gender',
  'assist.aadhaar',
  'assist.mobile',
  'assist.address',
  'assist.employment',
  'assist.education',
  'assist.scheme',
  'assist.member.add',
  'assist.member.name',
  'assist.member.relation',
  'assist.member.gender',
  'assist.member.dob',
  'assist.member.aadhaar',
  'assist.member.mobile',
  'assist.member.address',
  'assist.member.more',
  'assist.field.pan',
  'assist.field.epic',
  'assist.field.ration',
  'assist.field.bankName',
  'assist.field.bankAccount',
  'assist.field.bankIfsc',
  'assist.review.title',
  'assist.preview.title',
  'assist.download.title'
] as const;

export type AudioPromptKey = (typeof audioManifest)[number];
